#!/bin/bash

SCRIPTPATH=`dirname $(realpath $0)`
LIBPATH=`realpath $SCRIPTPATH/../lib`
CP="$LIBPATH/classes"

if [ $# == 0 ]; then
    echo "For generator options type 'qualification -help'"
fi

exec java -cp "$CP" -Xmx256M benchmark.qualification.Qualification "$@"
